# Site settings
title: Unveillance
email: harlo.holmes@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Development blog for the Unveillance team.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://unveillance.github.io" # the base hostname & protocol for your site
twitter_username: harlo
github_username:  unveillance

# Build settings
markdown: redcarpet
highlighter: pygments
defaults:
  -
    scope:
      type: "posts"
    values:
      permalink: :year/:month/:day/:title.html